#include "Template.hpp"

std::string Template::Error(int code, std::string message)
{
    std::ostringstream html;

    html <<
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"UTF-8\" />\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
        "  <title>" << code << " | " << message<< "</title>\n"
        "  <style>\n"
        "    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
        "    :root {\n"
        "      --bg: #0a0a0a; --fg: #ededed; --muted: #888888;\n"
        "      --border: #2a2a2a;\n"
        "      --font: 'Geist', 'Inter', system-ui, -apple-system, sans-serif;\n"
        "      --mono: 'Geist Mono', 'Fira Code', 'Menlo', monospace;\n"
        "    }\n"
        "    html, body { height: 100%; }\n"
        "    body {\n"
        "      background: var(--bg); color: var(--fg);\n"
        "      font-family: var(--font);\n"
        "      display: flex; flex-direction: column;\n"
        "      align-items: center; justify-content: center;\n"
        "      min-height: 100vh; padding: 2rem;\n"
        "    }\n"
        "    .wrapper {\n"
        "      display: flex; align-items: center;\n"
        "      gap: 2rem; max-width: 480px; width: 100%;\n"
        "    }\n"
        "    .code {\n"
        "      font-family: var(--mono); font-size: 1.75rem;\n"
        "      font-weight: 600; white-space: nowrap;\n"
        "      padding-right: 2rem;\n"
        "      border-right: 1px solid var(--border); line-height: 1;\n"
        "    }\n"
        "    .info { display: flex; flex-direction: column; gap: 0.25rem; }\n"
        "    .message { font-size: 0.9rem; font-weight: 400; }\n"
        "    .sub { font-size: 0.78rem; color: var(--muted); }\n"
        "    a { color: var(--fg); text-decoration: underline; text-underline-offset: 3px; }\n"
        "    a:hover { color: var(--muted); }\n"
        "    footer {\n"
        "      position: fixed; bottom: 1.5rem;\n"
        "      font-size: 0.72rem; color: var(--muted);\n"
        "      font-family: var(--mono); letter-spacing: 0.03em;\n"
        "    }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <div class=\"wrapper\">\n"
        "    <div class=\"code\">" << code << "</div>\n"
        "    <div class=\"info\">\n"
        "      <p class=\"message\">" << message << "</p>\n"
        "      <p class=\"sub\"><a href=\"/\">Return to home</a></p>\n"
        "    </div>\n"
        "  </div>\n"
        "  <footer>server &middot; http/1.1</footer>\n"
        "</body>\n"
        "</html>\n";

    return (html.str());
}
